import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

/**
 * Universal PDF Generator Class
 * 通用PDF生成器，支持智能分页、进度跟踪和多种文档类型
 */
export class PDFGenerator {
  constructor(options = {}) {
    // 基础配置
    this.options = {
      pageSize: 'a4',
      orientation: 'portrait',
      unit: 'mm',
      margins: {
        top: 20,
        bottom: 25,
        left: 10,
        right: 10
      },
      progressCallback: null,
      enableCache: true,
      quality: 'high',
      ...options
    }

    // PDF实例
    this.pdf = null
    
    // 页面尺寸 (A4)
    this.pageWidth = 210
    this.pageHeight = 297
    this.contentWidth = this.pageWidth - this.options.margins.left - this.options.margins.right

    // 进度跟踪
    this.progressCallback = this.options.progressCallback
    this.currentProgress = 0

    // 性能配置
    this.performanceConfig = {
      canvasScale: this.options.quality === 'high' ? 2 : 1.5,
      batchSize: 10,
      memoryThreshold: 100 * 1024 * 1024,
      enableCache: this.options.enableCache,
      maxCacheSize: 50 * 1024 * 1024
    }

    // 缓存管理
    this.cache = new Map()
    this.cacheSize = 0

    // 性能监控
    this.startTime = null
    this.memoryUsage = 0

    // 页面内容跟踪
    this.pageContentInfo = []
    this.contentPageCount = 0
  }

  /**
   * 生成PDF文档
   * @param {Object} content - 文档内容配置
   * @param {Object} template - 模板配置
   * @returns {Promise<string>} PDF预览URL
   */
  async generatePDF(content, template = {}) {
    try {
      this.updateProgress(5, 'Initializing PDF generator...')
      
      // 开始性能监控
      this.startPerformanceMonitoring()

      // 创建PDF实例
      this.pdf = new jsPDF(
        this.options.orientation,
        this.options.unit,
        this.options.pageSize
      )

      // 设置PDF文档属性
      this.setupDocumentProperties(content.metadata || {})

      this.updateProgress(10, 'PDF generator initialized')

      // 添加封面页（如果需要）
      if (content.cover) {
        await this.addCoverPage(content.cover)
      }

      // 添加内容页面
      await this.addContentPages(content, template)

      // 优化页面布局
      await this.optimizePageLayout()

      this.updateProgress(100, 'PDF generation completed!')

      // 结束性能监控
      this.endPerformanceMonitoring()

      // 生成PDF的Blob URL
      const pdfBlob = this.pdf.output('blob')
      this.pdfBlob = pdfBlob
      const pdfUrl = URL.createObjectURL(pdfBlob)

      return pdfUrl
    } catch (error) {
      console.error('PDF generation failed:', error)
      throw new Error('PDF generation failed: ' + error.message)
    }
  }

  /**
   * 设置PDF文档属性
   */
  setupDocumentProperties(metadata) {
    this.pdf.setProperties({
      title: metadata.title || 'Generated Document',
      subject: metadata.subject || 'Document generated by Universal PDF Generator',
      author: metadata.author || 'Universal PDF Generator',
      creator: metadata.creator || 'Universal PDF Generator v1.0.0',
      producer: metadata.producer || 'Universal PDF Generator v1.0.0'
    })
  }

  /**
   * 更新进度
   */
  updateProgress(progress, message) {
    this.currentProgress = Math.max(0, Math.min(100, progress))
    
    if (this.progressCallback) {
      this.progressCallback(this.currentProgress, message)
    }

    console.log(`Progress: ${this.currentProgress}% - ${message}`)
  }

  /**
   * 性能监控 - 开始
   */
  startPerformanceMonitoring() {
    this.startTime = performance.now()
    if (performance.memory) {
      this.memoryUsage = performance.memory.usedJSHeapSize
      console.log('📊 Performance monitoring started - Memory usage:', this.formatBytes(this.memoryUsage))
    }
  }

  /**
   * 性能监控 - 结束
   */
  endPerformanceMonitoring() {
    if (this.startTime) {
      const duration = performance.now() - this.startTime
      console.log(`⚡ PDF generation completed - Duration: ${duration.toFixed(2)}ms`)

      if (performance.memory) {
        const currentMemory = performance.memory.usedJSHeapSize
        const memoryDiff = currentMemory - this.memoryUsage
        console.log(`💾 Memory usage: ${this.formatBytes(currentMemory)} (Growth: ${this.formatBytes(memoryDiff)})`)
      }
    }
  }

  /**
   * 格式化字节大小
   */
  formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes'
    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
  }

  /**
   * 添加封面页
   */
  async addCoverPage(coverConfig) {
    try {
      this.updateProgress(15, 'Creating cover page...')

      if (coverConfig.type === 'image' && coverConfig.url) {
        // 图片封面
        const coverElement = this.createImageCoverElement(coverConfig.url)
        document.body.appendChild(coverElement)

        const canvas = await html2canvas(coverElement, {
          scale: this.performanceConfig.canvasScale,
          useCORS: true,
          allowTaint: true,
          backgroundColor: null
        })

        const imgData = canvas.toDataURL('image/png')
        this.pdf.addImage(imgData, 'PNG', 0, 0, this.pageWidth, this.pageHeight)

        document.body.removeChild(coverElement)
      } else if (coverConfig.type === 'custom' && coverConfig.html) {
        // 自定义HTML封面
        await this.addCustomCoverPage(coverConfig.html)
      }

      this.updateProgress(25, 'Cover page added')
    } catch (error) {
      console.error('Cover page generation failed:', error)
    }
  }

  /**
   * 创建图片封面元素
   */
  createImageCoverElement(imageUrl) {
    const coverDiv = document.createElement('div')
    coverDiv.style.cssText = `
      position: absolute;
      top: -9999px;
      left: -9999px;
      width: 210mm;
      height: 297mm;
      background: url('${imageUrl}') no-repeat center center;
      background-size: cover;
      padding: 0;
      margin: 0;
    `
    return coverDiv
  }

  /**
   * 添加内容页面
   */
  async addContentPages(content, template) {
    this.updateProgress(30, 'Processing content...')
    
    // 添加新页面
    this.pdf.addPage()

    // 创建内容元素
    const contentElement = this.createContentElement(content, template)
    document.body.appendChild(contentElement)

    try {
      this.updateProgress(50, 'Rendering content...')

      // 使用html2canvas生成内容图片
      const canvas = await html2canvas(contentElement, {
        scale: this.performanceConfig.canvasScale,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        height: contentElement.scrollHeight,
        windowHeight: contentElement.scrollHeight
      })

      this.updateProgress(70, 'Processing pagination...')

      const imgData = canvas.toDataURL('image/png')
      const imgWidth = this.contentWidth
      const imgHeight = (canvas.height * imgWidth) / canvas.width

      // 智能分页处理
      await this.addContentWithPagination(imgData, imgWidth, imgHeight, contentElement)
    } finally {
      document.body.removeChild(contentElement)
    }
  }

  /**
   * 创建通用内容元素
   */
  createContentElement(content, template) {
    const contentDiv = document.createElement('div')
    const contentWidthMM = this.contentWidth
    const contentWidthPX = Math.round(contentWidthMM * 3.7795275591)

    contentDiv.style.cssText = `
      position: absolute;
      top: -9999px;
      left: -9999px;
      width: ${contentWidthPX}px;
      padding: 0;
      margin: 0;
      background: white;
      font-family: ${template.fontFamily || "'Arial', sans-serif"};
      font-size: ${template.fontSize || '12pt'};
      line-height: ${template.lineHeight || '1.4'};
      color: ${template.textColor || '#333'};
      box-sizing: border-box;
      word-wrap: break-word;
      overflow-wrap: break-word;
    `

    // 根据内容类型生成HTML
    if (typeof content.body === 'string') {
      contentDiv.innerHTML = content.body
    } else if (typeof content.body === 'object') {
      contentDiv.innerHTML = this.generateHTMLFromStructure(content.body, template)
    }

    return contentDiv
  }

  /**
   * 从结构化数据生成HTML
   */
  generateHTMLFromStructure(structure, template) {
    // 这里可以根据不同的数据结构生成相应的HTML
    // 具体实现可以在子类中扩展
    if (structure.type === 'exam') {
      return this.generateExamHTML(structure, template)
    } else if (structure.type === 'report') {
      return this.generateReportHTML(structure, template)
    } else {
      return this.generateGenericHTML(structure, template)
    }
  }

  /**
   * 生成通用HTML
   */
  generateGenericHTML(structure, template) {
    let html = ''
    
    if (structure.title) {
      html += `<h1 style="text-align: center; margin-bottom: 30px; color: ${template.primaryColor || '#333'};">${structure.title}</h1>`
    }

    if (structure.sections) {
      structure.sections.forEach(section => {
        html += `<div style="margin-bottom: 20px;">`
        if (section.title) {
          html += `<h2 style="color: ${template.secondaryColor || '#666'}; margin-bottom: 15px;">${section.title}</h2>`
        }
        if (section.content) {
          html += `<div>${section.content}</div>`
        }
        html += `</div>`
      })
    }

    return html
  }

  /**
   * 智能分页处理
   */
  async addContentWithPagination(imgData, imgWidth, imgHeight, contentElement) {
    const pageHeight = this.pageHeight
    const topMargin = this.options.margins.top
    const bottomMargin = this.options.margins.bottom
    const usablePageHeight = pageHeight - topMargin - bottomMargin

    let currentY = 0
    let pageCount = 0

    while (currentY < imgHeight) {
      const nextBreak = Math.min(currentY + usablePageHeight, imgHeight)
      const adjustedBreak = this.findSafePageBreak(currentY, nextBreak, contentElement, imgHeight)
      
      await this.addPageContent(imgData, imgWidth, imgHeight, currentY, adjustedBreak, pageCount, topMargin)
      
      currentY = adjustedBreak
      pageCount++

      // 更新进度
      const progress = 70 + (currentY / imgHeight) * 20
      this.updateProgress(Math.round(progress), `Processing page ${pageCount}...`)

      if (currentY < imgHeight) {
        this.pdf.addPage()
      }
    }

    this.contentPageCount = pageCount
    this.updateProgress(90, 'Adding page numbers...')
    
    // 添加页码
    await this.addPageNumbers(pageCount)
  }

  /**
   * 寻找安全的分页点
   */
  findSafePageBreak(startY, endY, contentElement, imgHeight) {
    if (endY >= imgHeight) {
      return imgHeight
    }
    // 这里可以实现更智能的分页逻辑
    return endY
  }

  /**
   * 添加页面内容
   */
  async addPageContent(imgData, imgWidth, imgHeight, startY, endY, pageCount, topMargin) {
    try {
      const canvas = document.createElement('canvas')
      const ctx = canvas.getContext('2d')
      const img = new Image()
      img.src = imgData

      await new Promise((resolve, reject) => {
        img.onload = resolve
        img.onerror = reject
      })

      const scale = img.height / imgHeight
      const actualStartY = startY * scale
      const actualEndY = endY * scale
      const actualHeight = actualEndY - actualStartY

      canvas.width = img.width
      canvas.height = actualHeight

      ctx.drawImage(
        img,
        0, actualStartY, img.width, actualHeight,
        0, 0, canvas.width, canvas.height
      )

      const pageImgData = canvas.toDataURL('image/PNG')
      const pageImgWidth = this.contentWidth
      const pageImgHeight = (actualHeight * pageImgWidth) / img.width
      const x = this.options.margins.left

      if (pageCount === 0) {
        this.pdf.addImage(pageImgData, 'PNG', x, topMargin, pageImgWidth, pageImgHeight)
      } else {
        this.pdf.addImage(pageImgData, 'PNG', x, topMargin, pageImgWidth, pageImgHeight)
      }
    } catch (error) {
      console.error('Page content addition failed:', error)
    }
  }

  /**
   * 添加页码
   */
  async addPageNumbers(totalPages) {
    for (let i = 1; i <= totalPages; i++) {
      this.pdf.setPage(i + 1) // +1 because of cover page
      this.addPageNumber(i, totalPages)
    }
  }

  /**
   * 添加单个页码
   */
  addPageNumber(currentPage, totalPages) {
    this.pdf.setFont('helvetica', 'normal')
    this.pdf.setFontSize(10)
    this.pdf.setTextColor(100, 100, 100)

    const pageText = `${currentPage}`
    const textWidth = this.pdf.getTextWidth(pageText)
    const x = (this.pageWidth - textWidth) / 2
    const y = this.pageHeight - this.options.margins.bottom + 12

    this.pdf.text(pageText, x, y)
  }

  /**
   * 优化页面布局
   */
  async optimizePageLayout() {
    this.updateProgress(95, 'Optimizing page layout...')
    
    const totalPages = this.pdf.internal.getNumberOfPages()
    
    // 如果是奇数页，可以选择添加空白页
    if (totalPages % 2 === 1 && this.options.addBlankPageForEven) {
      this.pdf.addPage()
      this.addBlankPageWatermark()
    }
  }

  /**
   * 添加空白页标识
   */
  addBlankPageWatermark() {
    // 空白页保持完全空白，或者添加极淡的标识
    // 根据需要可以在这里添加实现
  }

  /**
   * 下载PDF文件
   */
  downloadPDF(filename = 'document.pdf') {
    if (this.pdfBlob) {
      const link = document.createElement('a')
      link.href = URL.createObjectURL(this.pdfBlob)
      link.download = filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(link.href)
    } else {
      throw new Error('No PDF file available for download')
    }
  }

  /**
   * 获取PDF作为Base64字符串
   */
  getPDFAsBase64() {
    if (this.pdf) {
      return this.pdf.output('datauristring')
    }
    throw new Error('No PDF generated')
  }

  /**
   * 获取PDF作为Blob
   */
  getPDFAsBlob() {
    if (this.pdf) {
      return this.pdf.output('blob')
    }
    throw new Error('No PDF generated')
  }

  /**
   * 清理资源
   */
  cleanup() {
    if (this.pdfBlob) {
      URL.revokeObjectURL(this.pdfBlob)
    }
    this.cache.clear()
    this.cacheSize = 0
    this.pdf = null
  }
} 